In [3]:
# pip install yfinance

In [4]:
import yfinance as yf

In [5]:
from datetime import datetime
end = datetime.now()
start = datetime(end.year-20, end.month, end.day)

In [6]:
stock = "GOOG"
google_data = yf.download(stock, start, end)

[*********************100%***********************]  1 of 1 completed


In [7]:
google_data.head()

Price      Adj Close     Close      High       Low      Open     Volume
Ticker          GOOG      GOOG      GOOG      GOOG      GOOG       GOOG
Date                                                                   
2005-01-03  5.030750  5.048826  5.071989  4.868253  4.916571  636143518
2005-01-04  4.826999  4.844342  5.054305  4.818937  5.016198  552298420
2005-01-05  4.802429  4.819685  4.904118  4.787804  4.818190  330698912
2005-01-06  4.679335  4.696148  4.879212  4.675475  4.858788  417041336
2005-01-07  4.810867  4.828153  4.838116  4.701876  4.748203  387964757

In [8]:
google_data.shape

(5033, 6)

In [9]:
google_data.describe()

Price     Adj Close        Close         High          Low         Open  \
Ticker         GOOG         GOOG         GOOG         GOOG         GOOG   
count   5033.000000  5033.000000  5033.000000  5033.000000  5033.000000   
mean      48.557006    48.721578    49.214235    48.213627    48.700322   
std       46.457020    46.596970    47.082267    46.106519    46.565803   
min        4.342810     4.358414     4.443345     4.298140     4.366135   
25%       13.288515    13.336262    13.485951    13.213224    13.374868   
50%       28.048210    28.148991    28.435431    27.876465    28.182125   
75%       64.370209    64.601501    64.965500    63.950001    64.473000   
max      198.160004   198.160004   202.880005   196.690002   198.529999   

Price         Volume  
Ticker          GOOG  
count   5.033000e+03  
mean    1.090427e+08  
std     1.422561e+08  
min     1.584340e+05  
25%     2.658400e+07  
50%     5.058490e+07  
75%     1.328240e+08  
max     1.650833e+09

In [10]:
google_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5033 entries, 2005-01-03 to 2024-12-31
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   (Adj Close, GOOG)  5033 non-null   float64
 1   (Close, GOOG)      5033 non-null   float64
 2   (High, GOOG)       5033 non-null   float64
 3   (Low, GOOG)        5033 non-null   float64
 4   (Open, GOOG)       5033 non-null   float64
 5   (Volume, GOOG)     5033 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 275.2 KB


In [11]:
google_data.isna().sum()

Price      Ticker
Adj Close  GOOG      0
Close      GOOG      0
High       GOOG      0
Low        GOOG      0
Open       GOOG      0
Volume     GOOG      0
dtype: int64

In [12]:
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
plt.figure(figsize = (15,5))
google_data['Adj Close'].plot()
plt.xlabel("years")
plt.ylabel("Adj Close")
plt.title("Closing price of Google data")

Text(0.5, 1.0, 'Closing price of Google data')

In [14]:
def plot_graph(figsize, values, column_name):
    plt.figure()
    values.plot(figsize = figsize)
    plt.xlabel("years")
    plt.ylabel(column_name)
    plt.title(f"{column_name} of Google data")
    

In [15]:
google_data.columns

MultiIndex([('Adj Close', 'GOOG'),
            (    'Close', 'GOOG'),
            (     'High', 'GOOG'),
            (      'Low', 'GOOG'),
            (     'Open', 'GOOG'),
            (   'Volume', 'GOOG')],
           names=['Price', 'Ticker'])

In [16]:
for column in google_data.columns:
    plot_graph((15,5),google_data[column], column)

In [17]:
# 10, 20, 30, 40, 50, 60, 70, 80, 90, 100

# MA for 5 days ==> null null null null 30 40 50 60 70 80

In [18]:
temp_data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(sum(temp_data[1:6])/5)

40.0


In [19]:
import pandas as pd
data = pd.DataFrame([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
data.head()

0
0  10
1  20
2  30
3  40
4  50

In [20]:
data['MA'] = data.rolling(5).mean()
data

0    MA
0   10   NaN
1   20   NaN
2   30   NaN
3   40   NaN
4   50  30.0
5   60  40.0
6   70  50.0
7   80  60.0
8   90  70.0
9  100  80.0

In [21]:
for i in range(2004,2025):
    print(i,list(google_data.index.year).count(i))

2004 0
2005 252
2006 251
2007 251
2008 253
2009 252
2010 252
2011 252
2012 250
2013 252
2014 252
2015 252
2016 252
2017 251
2018 251
2019 252
2020 253
2021 252
2022 251
2023 250
2024 252


In [22]:
google_data['MA_for_250_days'] = google_data['Adj Close'].rolling(250).mean()

In [23]:
google_data['MA_for_250_days'][0:250].tail()

Date
2005-12-21         NaN
2005-12-22         NaN
2005-12-23         NaN
2005-12-27         NaN
2005-12-28    6.865533
Name: MA_for_250_days, dtype: float64

In [24]:
plot_graph((15,5), google_data['MA_for_250_days'], 'MA_for_250_days')

In [25]:
plot_graph((15,5), google_data[['Adj Close','MA_for_250_days']], 'MA_for_250_days')

In [26]:
google_data['MA_for_100_days'] = google_data['Adj Close'].rolling(100).mean()
plot_graph((15,5), google_data[['Adj Close','MA_for_100_days']], 'MA_for_100_days')

In [27]:
plot_graph((15,5), google_data[['Adj Close','MA_for_100_days', 'MA_for_250_days']], 'MA')

In [28]:
google_data['percentage_change_cp'] = google_data['Adj Close'].pct_change()
google_data[['Adj Close','percentage_change_cp']].head()

Price      Adj Close percentage_change_cp
Ticker          GOOG                     
Date                                     
2005-01-03  5.030750                  NaN
2005-01-04  4.826999            -0.040501
2005-01-05  4.802429            -0.005090
2005-01-06  4.679335            -0.025632
2005-01-07  4.810867             0.028109

In [29]:
plot_graph((15,5), google_data['percentage_change_cp'], 'percentage_change')

In [30]:
Adj_close_price = google_data[['Adj Close']]

In [31]:
max(Adj_close_price.values),min(Adj_close_price.values) 

(array([198.16000366]), array([4.34281015]))

In [32]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(Adj_close_price)
scaled_data

array([[0.00354943],
       [0.00249817],
       [0.0023714 ],
       ...,
       [0.9787428 ],
       [0.97177752],
       [0.96016865]])

In [33]:
len(scaled_data)

5033

In [34]:
x_data = []
y_data = []

for i in range(100, len(scaled_data)):
    x_data.append(scaled_data[i-100:i])
    y_data.append(scaled_data[i])
    
import numpy as np
x_data, y_data = np.array(x_data), np.array(y_data)

In [35]:
x_data[0],y_data[0]

(array([[3.54942527e-03],
        [2.49817133e-03],
        [2.37140491e-03],
        [1.73629842e-03],
        [2.41494135e-03],
        [2.56987508e-03],
        [2.37524535e-03],
        [2.61085041e-03],
        [2.60444640e-03],
        [3.19858495e-03],
        [3.70180280e-03],
        [2.85669991e-03],
        [2.42390155e-03],
        [1.70172464e-03],
        [7.33700686e-04],
        [2.72737484e-04],
        [1.82464570e-03],
        [1.67611844e-03],
        [1.96549946e-03],
        [2.64158129e-03],
        [2.16525141e-03],
        [3.96557270e-03],
        [4.59299833e-03],
        [3.76070345e-03],
        [2.69407793e-03],
        [3.02827963e-03],
        [2.12427609e-03],
        [1.66331289e-03],
        [1.58904311e-03],
        [2.30482093e-03],
        [2.59164084e-03],
        [2.99882808e-03],
        [2.93352834e-03],
        [2.93992743e-03],
        [2.09738564e-03],
        [2.42774691e-03],
        [1.77983240e-03],
        [1.39313651e-03],
        [1.6

In [36]:

int(len(x_data)*0.7)

3453

In [37]:
4908-100-int(len(x_data)*0.7)

1355

In [38]:
splitting_len = int(len(x_data)*0.7)
x_train = x_data[:splitting_len]
y_train = y_data[:splitting_len]

x_test = x_data[splitting_len:]
y_test = y_data[splitting_len:]

In [39]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3453, 100, 1)
(3453, 1)
(1480, 100, 1)
(1480, 1)


In [40]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [41]:
model = Sequential()
model.add(LSTM(128, return_sequences=True, input_shape=(x_train.shape[1],1)))
model.add(LSTM(64,return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

c:\Users\bhargav\ML\anaconda\envs\tensorflow_env\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [42]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [43]:
model.fit(x_train, y_train, batch_size=1, epochs = 2)

Epoch 1/2
3453/3453 ━━━━━━━━━━━━━━━━━━━━ 97s 27ms/step - loss: 2.3369e-04
Epoch 2/2
3453/3453 ━━━━━━━━━━━━━━━━━━━━ 122s 35ms/step - loss: 5.3382e-05


In [44]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 100, 128)       │        66,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 25)             │         1,625 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 352,859 (1.35 MB)

 Trainable params: 117,619 (459.45 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 235,240 (918.91 KB)

In [45]:
predictions = model.predict(x_test)

47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step


In [46]:
predictions

array([[0.26784292],
       [0.26878974],
       [0.26772186],
       ...,
       [0.9098584 ],
       [0.90023255],
       [0.89160305]], dtype=float32)

In [47]:
inv_predictions = scaler.inverse_transform(predictions)
inv_predictions

array([[ 56.25537],
       [ 56.43888],
       [ 56.23191],
       ...,
       [180.68901],
       [178.82336],
       [177.15082]], dtype=float32)

In [48]:
inv_y_test = scaler.inverse_transform(y_test)
inv_y_test

array([[ 55.8827095 ],
       [ 55.48314285],
       [ 55.72776794],
       ...,
       [194.03999329],
       [192.69000244],
       [190.44000244]])

In [49]:
rmse = np.sqrt(np.mean( (inv_predictions - inv_y_test)**2))

In [50]:
rmse

5.545826379363169

In [51]:
ploting_data = pd.DataFrame(
 {
  'original_test_data': inv_y_test.reshape(-1),
    'predictions': inv_predictions.reshape(-1)
 } ,
    index = google_data.index[splitting_len+100:]
)
ploting_data.head()

original_test_data  predictions
Date                                       
2019-02-14           55.882710    56.255371
2019-02-15           55.483143    56.438881
2019-02-19           55.727768    56.231911
2019-02-20           55.490616    56.186451
2019-02-21           54.652130    56.065849

In [52]:
plot_graph((15,6), ploting_data, 'test data')

In [53]:
plot_graph((15,6), pd.concat([Adj_close_price[:splitting_len+100],ploting_data], axis=0), 'whole data')

In [54]:
model.save("Latest_stock_price_model.keras")